// Generated by CoffeeScript 1.3.3

buster.testCase("ConnectivityMap with maps loaded", {
  setUp: function() {
    window.google = {};
    window.google.maps = {};
    return this.map = Ext.create('RfTouch.ConnectivityMap');
  },
  tearDown: function() {
    delete window.google.maps;
    delete window.google;
    return this.map.destroy();
  },
  "Map gets masked when offline event is fired": function() {
    var eventSimulation, map;
    map = this.map;
    eventSimulation = function() {
      return map.setOnline.call(map, false);
    };
    this.stub(map, "setMasked");
    eventSimulation();
    assert.calledOnce(map.setMasked);
    return assert.calledWith(map.setMasked, map.getOfflineMask());
  },
  "Map gets unmasked when online is fired after offline": function() {
    var eventSimulation, map;
    map = this.map;
    eventSimulation = function() {
      return map.setOnline.call(map, true);
    };
    this.stub(map, "setMasked");
    eventSimulation();
    assert.calledOnce(map.setMasked);
    return assert.calledWith(map.setMasked, false);
  },
  "online calls setOnline with true": function() {
    var map;
    map = this.map;
    this.stub(map, "setOnline");
    map.online();
    assert.calledOnce(map.setOnline);
    return assert.calledWith(map.setOnline, true);
  },
  "offline calls setOnline with false": function() {
    var map;
    map = this.map;
    this.stub(map, "setOnline");
    map.offline();
    assert.calledOnce(map.setOnline);
    return assert.calledWith(map.setOnline, false);
  }
});

buster.testCase("ConnectivityMap with maps not loaded", {
  setUp: function() {
    return this.map = Ext.create('RfTouch.ConnectivityMap');
  },
  tearDown: function() {
    return this.map.destroy();
  },
  "When going online the map loads Google maps": function() {
    var map;
    map = this.map;
    this.stub(map, "loadMaps");
    this.stub(map, "setMasked");
    map.online();
    assert.calledOnce(map.loadMaps);
    return refute.called(map.setMasked);
  },
  "When loadMaps is run it adds the google maps call to the head": function() {
    this.stub(document.head, "appendChild");
    return assert.called(document.head.appendChild);
  },
  "The callback is executed when the script is loaded": function() {
    return this.stub(window.rohdef.rftouch, "gmap_cb");
  },
  "The callback shows the map": function() {}
});
