// Generated by CoffeeScript 1.3.3
/**
  Simple frame for the ConnectivityMap
*/

Ext.define("RfTouch.ConnectivityMap", {
  extend: 'Ext.Panel',
  config: {
    ownLocation: false,
    offlineMask: {
      xtype: 'loadmask',
      message: 'Please connect to the internet to use the map.'
    }
  },
  setOnline: function(online) {
    if (online) {
      return this.setMasked(false);
    } else {
      return this.setMasked(this.getOfflineMask());
    }
  }
});
