// Generated by CoffeeScript 1.3.3
var config;

config = module.exports;

config["My tests"] = {
  rootPath: "../",
  environment: "browser",
  resources: ["RfTouch/*.js", "RfTouch/*/*.js", "test-setup/app/*/*.js", "test-setup/app/*/*/*.js", "test-setup/res/*"],
  sources: ["test-setup/touch/sencha-touch-all.js", "test-setup/app.js"],
  tests: ["test/*/*-test.js", "test/*-test.js"]
};
