// Generated by CoffeeScript 1.3.3

Ext.define("RfTouchTest.model.Person", {
  extend: 'Ext.data.Model',
  config: {
    fields: [
      {
        name: 'firstName',
        type: 'string'
      }, {
        name: 'lastName',
        type: 'string'
      }, {
        name: 'age',
        type: 'int'
      }
    ]
  }
});
